import type { AnnotatedGame } from '../types'

const operaGame: AnnotatedGame = {
  id: 'opera-game',
  title: "Morphy's Opera Game",
  white: 'Paul Morphy',
  black: 'Duke of Brunswick & Count Isouard',
  event: 'Paris, 1858',
  result: '1-0',
  sourceUrl: 'https://en.wikipedia.org/wiki/Opera_Game',
  moves: [
    { san: 'e4', explanation: 'White claims central space and opens lines for the queen and bishop.' },
    { san: 'e5', explanation: 'Black mirrors the central claim and frees the king bishop.' },
    { san: 'Nf3', explanation: 'The knight develops with tempo by attacking e5.' },
    { san: 'd6', explanation: 'Philidor\'s Defence supports e5, but temporarily blocks the dark-squared bishop.' },
    { san: 'd4', explanation: 'Morphy challenges the center before Black can finish developing.' },
    { san: 'Bg4', explanation: 'Black pins the knight, but develops a piece that will soon be exchanged.' },
    { san: 'dxe5', explanation: 'White opens the center while Black\'s king is still in the middle.' },
    { san: 'Bxf3', explanation: 'Black gives up the bishop to damage coordination, but surrenders a developed piece.' },
    { san: 'Qxf3', explanation: 'The queen recaptures, preserves the pawn structure, and points at f7.' },
    { san: 'dxe5', explanation: 'Black restores the material balance but leaves White far ahead in development.' },
    { san: 'Bc4', explanation: 'The bishop develops to its most active diagonal and adds pressure to f7.' },
    { san: 'Nf6', explanation: 'A natural developing move, but it does not meet the coming double attack on f7 and b7.' },
    { san: 'Qb3', explanation: 'The queen creates two threats at once: pressure on f7 and an attack on b7.' },
    { san: 'Qe7', explanation: 'Black defends f7, but blocks the bishop and makes castling harder.' },
    { san: 'Nc3', explanation: 'Morphy values development and initiative more than grabbing the b7 pawn.' },
    { san: 'c6', explanation: 'Black supports d5 and gives the queen a possible defensive route.' },
    { san: 'Bg5', explanation: 'The bishop pins the f6-knight to the queen and increases the central pressure.' },
    { san: 'b5', explanation: 'Black attacks the bishop, but the pawn push creates a tactical target.' },
    { san: 'Nxb5', explanation: 'Morphy sacrifices the knight to keep lines open and prevent Black from catching up in development.' },
    { san: 'cxb5', explanation: 'Black accepts the sacrifice, opening the b-file and the bishop\'s route to b5.' },
    { san: 'Bxb5+', explanation: 'The bishop recaptures with check and pins the king in the center.' },
    { san: 'Nbd7', explanation: 'The knight blocks the check, but becomes pinned and overloaded.' },
    { san: 'O-O-O', explanation: 'White castles with tempo: the king becomes safe and the rook joins the open d-file.' },
    { san: 'Rd8', explanation: 'Black contests the file, but the pieces behind the rook remain awkwardly pinned.' },
    { san: 'Rxd7', explanation: 'White removes a defender and forces the other rook onto the vulnerable d-file.' },
    { san: 'Rxd7', explanation: 'Black must recapture, placing the rook in the bishop\'s pin.' },
    { san: 'Rd1', explanation: 'The remaining rook attacks the pinned d7-rook; every white piece is now active.' },
    { san: 'Qe6', explanation: 'Black tries to unpin the knight and offer a queen trade, but the attack is already decisive.' },
    { san: 'Bxd7+', explanation: 'White removes the rook with check and draws the knight onto d7.' },
    { san: 'Nxd7', explanation: 'The forced recapture leaves the back rank vulnerable to a final deflection.' },
    { san: 'Qb8+', explanation: 'The queen is offered to drag the knight away from d7 and clear the rook\'s mating square.' },
    { san: 'Nxb8', explanation: 'Black must take the checking queen, but the knight can no longer cover d8.' },
    { san: 'Rd8#', explanation: 'The rook delivers mate on the open file; Black\'s undeveloped pieces seal the king in.' },
  ],
}

const immortalGame: AnnotatedGame = {
  id: 'immortal-game',
  title: 'The Immortal Game',
  white: 'Adolf Anderssen',
  black: 'Lionel Kieseritzky',
  event: 'London, 1851',
  result: '1-0',
  sourceUrl: 'https://en.wikipedia.org/wiki/Immortal_Game',
  moves: [
    { san: 'e4', explanation: 'White occupies the center and releases the queen and bishop.' },
    { san: 'e5', explanation: 'Black answers symmetrically and also claims central space.' },
    { san: 'f4', explanation: 'The King\'s Gambit offers a pawn in exchange for open lines and faster development.' },
    { san: 'exf4', explanation: 'Black accepts the gambit and gains material, but gives White time to build an initiative.' },
    { san: 'Bc4', explanation: 'The Bishop\'s Gambit targets f7 and invites a check that will expose Black\'s queen.' },
    { san: 'Qh4+', explanation: 'Black checks and removes White\'s castling rights, but brings the queen out early.' },
    { san: 'Kf1', explanation: 'The king steps aside; White accepts the inconvenience to preserve attacking momentum.' },
    { san: 'b5', explanation: 'The Bryan Countergambit attacks the bishop, but modern analysis considers the pawn offer unsound.' },
    { san: 'Bxb5', explanation: 'White accepts and keeps the bishop active on the diagonal.' },
    { san: 'Nf6', explanation: 'Black develops and attacks e4 while preparing to chase the bishop.' },
    { san: 'Nf3', explanation: 'White develops with tempo by attacking the exposed queen.' },
    { san: 'Qh6', explanation: 'The queen retreats while continuing to support the advanced f4-pawn.' },
    { san: 'd3', explanation: 'White reinforces e4 and opens the c1-bishop.' },
    { san: 'Nh5', explanation: 'Black threatens ...Ng3+, but places the knight on the rim instead of developing a new piece.' },
    { san: 'Nh4', explanation: 'White challenges the queen\'s kingside squares and prepares Nf5.' },
    { san: 'Qg5', explanation: 'The queen stays active, but remains a target for White\'s developing moves.' },
    { san: 'Nf5', explanation: 'The knight reaches a powerful attacking post near the uncastled king.' },
    { san: 'c6', explanation: 'Black attacks the bishop and unpins the d-pawn, but still neglects development.' },
    { san: 'g4', explanation: 'White gains space and starts boxing in the queen, though the move is objectively risky.' },
    { san: 'Nf6', explanation: 'The knight returns toward the center and attacks g4.' },
    { san: 'Rg1', explanation: 'White deliberately leaves the bishop en prise; taking it will cost Black vital time.' },
    { san: 'cxb5', explanation: 'Black wins the bishop, but this material grab is the critical loss of time.' },
    { san: 'h4', explanation: 'The protected pawn attacks the queen and tightens the kingside net.' },
    { san: 'Qg6', explanation: 'The queen retreats along the only workable route.' },
    { san: 'h5', explanation: 'White chases the queen again and gains another tempo for the attack.' },
    { san: 'Qg5', explanation: 'The queen returns to g5, where White can create threats against both wings.' },
    { san: 'Qf3', explanation: 'White threatens to trap the queen with Bxf4 and to open a line toward a8 with e5.' },
    { san: 'Ng8', explanation: 'Black answers the threats by undeveloping; almost the entire army is back on its starting rank.' },
    { san: 'Bxf4', explanation: 'White recovers the gambit pawn and develops the last bishop with tempo.' },
    { san: 'Qf6', explanation: 'The queen escapes, but blocks the g8-knight and remains vulnerable.' },
    { san: 'Nc3', explanation: 'White brings another piece into the attack and controls d5.' },
    { san: 'Bc5', explanation: 'Black finally develops a piece and attacks the rook on g1.' },
    { san: 'Nd5', explanation: 'White ignores the rook threat to attack the queen and threaten a fork on c7.' },
    { san: 'Qxb2', explanation: 'Black grabs a pawn and threatens Qxa1+, focusing on material instead of king safety.' },
    { san: 'Bd6', explanation: 'The bishop blocks the queen\'s defensive diagonal and offers both white rooks.' },
    { san: 'Bxg1', explanation: 'Black takes the first rook, but the bishop leaves the defense and White\'s attack accelerates.' },
    { san: 'e5', explanation: 'The pawn blocks the queen out of the defense and creates a forced mating threat.' },
    { san: 'Qxa1+', explanation: 'Black takes the second rook with check, winning huge material but losing the king.' },
    { san: 'Ke2', explanation: 'The king calmly steps away; Black has no useful continuation against it.' },
    { san: 'Na6', explanation: 'The knight covers c7, attempting to stop the immediate mating pattern.' },
    { san: 'Nxg7+', explanation: 'The knight sacrifice opens the route for the bishop and drives the king to d8.' },
    { san: 'Kd8', explanation: 'The king is forced toward the center of the mating net.' },
    { san: 'Qf6+', explanation: 'White sacrifices the queen to remove the knight that guards e7.' },
    { san: 'Nxf6', explanation: 'Black must capture the checking queen, but this abandons the final mating square.' },
    { san: 'Be7#', explanation: 'The bishop mates: White\'s three minor pieces defeat Black\'s overwhelming material advantage.' },
  ],
}

export const annotatedGames = [operaGame, immortalGame]

const byId = new Map(annotatedGames.map((game) => [game.id, game]))

export function getAnnotatedGame(id: string | null | undefined) {
  return id ? byId.get(id) : undefined
}

export function getAnnotatedGameForSource(sourceUrl: string) {
  return annotatedGames.find((game) => game.sourceUrl === sourceUrl)
}
