// Maps each lesson slug to a query against the Lichess puzzle database.
//
// `any`    — puzzle must carry at least one of these themes (the motif).
// `all`    — puzzle must carry every one of these themes (usually a phase tag).
// `rating` — [min, max] Glicko band; defaults to the category band below.
//
// Theme keys are the canonical Lichess ones, from
// https://github.com/lichess-org/lila/blob/master/translation/source/puzzleTheme.xml
// A misspelled theme silently matches nothing, so `npm run import-puzzles`
// fails loudly if any query ends up under-filled.

/** Default Glicko band per category, used when a query sets no `rating`. */
export const CATEGORY_RATING = {
  fundamentals: [400, 1300],
  tactics: [800, 1800],
  calculation: [1700, 2500],
  positional: [1500, 2300],
  structures: [1400, 2300],
  endgames: [1100, 2200],
  mastery: [1900, 2600],
}

/**
 * Fallback when a slug has no entry below. Lessons about study habits, clock
 * management or notation have no tactical motif, so they draw a general
 * well-played puzzle from the category band rather than a wrong-themed one.
 */
export const CATEGORY_FALLBACK = {
  fundamentals: { any: ['mateIn1', 'hangingPiece', 'fork'] },
  tactics: { any: ['fork', 'pin', 'skewer', 'discoveredAttack'] },
  calculation: { any: ['sacrifice', 'attraction', 'deflection', 'quietMove'] },
  positional: { any: ['advantage', 'quietMove', 'trappedPiece'] },
  structures: { any: ['advantage', 'fork', 'pin'], all: ['opening'] },
  endgames: { any: ['endgame'] },
  mastery: { any: ['crushing', 'defensiveMove', 'quietMove'] },
}

/** How many puzzles to attach to each lesson. */
export const PUZZLES_PER_LESSON = 6

export const QUERIES = {
  // ---- fundamentals -------------------------------------------------------
  'fundamentals-algebraic-notation': { any: ['mateIn1'], rating: [400, 1000] },
  'fundamentals-attacked-squares': { any: ['hangingPiece'], rating: [400, 1100] },
  'fundamentals-board-orientation-light-square': { any: ['mateIn1'], rating: [400, 1000] },
  // `castling` is a rare tag, so this one needs the full rating range to fill.
  'fundamentals-castling-kingside-queenside': { any: ['castling'], rating: [400, 2200] },
  'fundamentals-check-three-legal-responses': { any: ['mateIn1'], rating: [400, 1000] },
  'fundamentals-checkmate': { any: ['mateIn1'], rating: [400, 1100] },
  'fundamentals-clocks-time-controls-flagging': { any: ['mateIn1', 'hangingPiece'] },
  'fundamentals-draws-repetition-fifty-move': { any: ['defensiveMove', 'equality'] },
  'fundamentals-en-passant': { any: ['enPassant'] },
  'fundamentals-files-ranks-square-names': { any: ['mateIn1'], rating: [400, 1000] },
  'fundamentals-how-bishop-moves-captures': { any: ['bodenMate', 'doubleBishopMate', 'hangingPiece'] },
  'fundamentals-how-king-moves': { any: ['mateIn1'], rating: [400, 1100] },
  'fundamentals-how-knight-moves-captures': { any: ['fork'], rating: [500, 1200] },
  'fundamentals-how-queen-moves-captures': { any: ['mateIn1', 'hangingPiece'], rating: [400, 1100] },
  'fundamentals-how-rook-moves-captures': { any: ['backRankMate'], rating: [500, 1200] },
  'fundamentals-pawn-captures': { any: ['hangingPiece', 'advancedPawn'], rating: [400, 1200] },
  'fundamentals-pawn-movement-two-square': { any: ['advancedPawn'], rating: [500, 1300] },
  'fundamentals-pawn-promotion-underpromotion': { any: ['promotion', 'underPromotion'] },
  'fundamentals-pieces-what-they-worth': { any: ['hangingPiece'], rating: [400, 1200] },
  'fundamentals-recording-game-reading-scoresheet': { any: ['mateIn1', 'fork'], rating: [400, 1100] },
  'fundamentals-resignation-draw-offers': { any: ['crushing'], rating: [500, 1300] },
  'fundamentals-stalemate': { any: ['defensiveMove', 'equality'] },
  'fundamentals-starting-position': { any: ['mateIn1'], rating: [400, 1000] },
  'fundamentals-when-castling-illegal': { any: ['castling', 'exposedKing'] },

  // ---- tactics ------------------------------------------------------------
  'tactics-alignments': { any: ['pin', 'skewer', 'xRayAttack'] },
  'tactics-attackers-defenders': { any: ['hangingPiece', 'capturingDefender'] },
  'tactics-attacking-pinned-piece': { any: ['pin'] },
  'tactics-attraction': { any: ['attraction'] },
  'tactics-back-rank-mate': { any: ['backRankMate'] },
  'tactics-batteries': { any: ['mateIn2', 'mateIn3'], all: ['sacrifice'] },
  'tactics-battery-mates': { any: ['hookMate', 'anastasiaMate', 'arabianMate', 'killBoxMate'] },
  'tactics-blunder-checks': { any: ['hangingPiece', 'defensiveMove'] },
  'tactics-board-safety-opponent-threats': { any: ['defensiveMove'] },
  'tactics-candidate-moves': { any: ['quietMove', 'crushing'] },
  'tactics-checks-captures-threats-scan': { any: ['fork', 'discoveredCheck', 'hangingPiece'] },
  'tactics-clearance': { any: ['clearance'] },
  'tactics-corridor-box-mates': { any: ['killBoxMate', 'backRankMate', 'hookMate'] },
  'tactics-defensive-tactics': { any: ['defensiveMove'] },
  'tactics-deflection': { any: ['deflection'] },
  'tactics-discovered-attacks': { any: ['discoveredAttack'] },
  'tactics-discovered-check': { any: ['discoveredCheck', 'doubleCheck'] },
  'tactics-double-attacks': { any: ['fork'] },
  'tactics-double-check': { any: ['doubleCheck'] },
  'tactics-escape-square-counting': { any: ['mateIn2'] },
  'tactics-forks': { any: ['fork'] },
  'tactics-hanging-pieces': { any: ['hangingPiece'] },
  'tactics-interference-blocking': { any: ['interference'] },
  'tactics-knight-forks': { any: ['fork', 'smotheredMate'] },
  'tactics-ladder-mate': { any: ['backRankMate', 'mateIn2'], all: ['endgame'] },
  'tactics-loose-pieces': { any: ['hangingPiece', 'trappedPiece'] },
  'tactics-mate-one': { any: ['mateIn1'] },
  'tactics-material-values-counting': { any: ['hangingPiece', 'capturingDefender'] },
  'tactics-overloading': { any: ['capturingDefender', 'deflection'] },
  'tactics-perpetual-check': { any: ['defensiveMove', 'equality'] },
  'tactics-pins-absolute-relative': { any: ['pin'] },
  'tactics-removal-defender': { any: ['capturingDefender'] },
  'tactics-safe-exchanges': { any: ['capturingDefender', 'hangingPiece'] },
  'tactics-simplification': { any: ['capturingDefender', 'advantage'] },
  'tactics-skewers': { any: ['skewer'] },
  'tactics-smothered-mate': { any: ['smotheredMate'] },
  'tactics-stalemate-as-saving-resource': { any: ['defensiveMove', 'equality'] },
  'tactics-x-rays': { any: ['xRayAttack'] },
  'tactics-zwischenzug': { any: ['intermezzo'] },

  // ---- calculation --------------------------------------------------------
  'calculation-board-reconstruction': { any: ['long', 'veryLong'] },
  'calculation-building-calculation-tree': { any: ['long', 'veryLong'] },
  'calculation-calculation-under-time-pressure': { any: ['mateIn2', 'mateIn3'] },
  'calculation-finding-opponents-best-defense': { any: ['defensiveMove', 'long'] },
  'calculation-forcing-moves-first': { any: ['sacrifice', 'attraction'] },
  'calculation-greek-gift': { any: ['sacrifice', 'kingsideAttack'], all: ['kingsideAttack'] },
  'calculation-judging-compensation': { any: ['sacrifice'] },
  'calculation-non-forcing-calculation': { any: ['quietMove'] },
  'calculation-opening-lines-against-uncastled': { any: ['exposedKing', 'attackingF2F7'] },
  'calculation-opposite-side-castling-attacks': { any: ['queensideAttack', 'kingsideAttack'] },
  'calculation-pawn-storms': { any: ['advancedPawn', 'kingsideAttack'] },
  'calculation-preconditions-attack': { any: ['exposedKing', 'kingsideAttack'] },
  'calculation-quiet-moves': { any: ['quietMove'] },
  'calculation-refutation-discipline': { any: ['defensiveMove', 'intermezzo'] },
  'calculation-rook-lifts': { any: ['kingsideAttack', 'mateIn3'] },
  'calculation-sacrifices-attack': { any: ['sacrifice'], all: ['middlegame'] },
  'calculation-same-side-castling-attacks': { any: ['kingsideAttack'] },
  'calculation-transitioning-out-attack': { any: ['advantage', 'crushing'] },
  'calculation-visualization': { any: ['veryLong', 'long'] },

  // ---- positional ---------------------------------------------------------
  'positional-bishop-knight': { any: ['trappedPiece', 'advantage'] },
  'positional-bishop-pair': { any: ['advantage', 'bishopEndgame'] },
  'positional-closed-centers': { any: ['quietMove', 'advantage'] },
  'positional-color-complexes': { any: ['bodenMate', 'doubleBishopMate', 'quietMove'] },
  'positional-complete-position-evaluation': { any: ['advantage', 'quietMove'] },
  'positional-detecting-opponents-plan': { any: ['defensiveMove'] },
  'positional-favorable-exchanges': { any: ['capturingDefender', 'advantage'] },
  'positional-fixed-centers': { any: ['quietMove', 'advantage'] },
  'positional-fluid-centers': { any: ['advancedPawn', 'advantage'] },
  'positional-good-bishop-bad-bishop': { any: ['bishopEndgame', 'trappedPiece'] },
  'positional-improving-your-worst-piece': { any: ['quietMove'] },
  'positional-major-piece-coordination': { any: ['queenRookEndgame', 'backRankMate'] },
  'positional-material-imbalances': { any: ['sacrifice', 'advantage'] },
  'positional-open-centers': { any: ['exposedKing', 'crushing'] },
  'positional-open-files': { any: ['backRankMate', 'rookEndgame'] },
  'positional-outposts': { any: ['fork', 'quietMove'] },
  'positional-pawn-breaks': { any: ['advancedPawn', 'clearance'] },
  'positional-principle-two-weaknesses': { any: ['advantage', 'quietMove'] },
  'positional-prophylaxis': { any: ['defensiveMove', 'quietMove'] },
  'positional-restriction': { any: ['trappedPiece', 'quietMove'] },
  'positional-seventh-rank': { any: ['backRankMate', 'rookEndgame'] },
  'positional-structural-transformation': { any: ['advancedPawn', 'advantage'] },
  'positional-technical-conversion': { any: ['crushing', 'advantage'], all: ['endgame'] },
  'positional-weak-pawns-isolated-doubled': { any: ['advantage', 'pawnEndgame'] },
  'positional-weak-squares-holes': { any: ['fork', 'quietMove'] },

  // ---- structures (openings) ---------------------------------------------
  'structures-benoni-structures': { any: ['advancedPawn', 'advantage'], all: ['opening'] },
  'structures-carlsbad-structure': { any: ['advantage', 'quietMove'] },
  'structures-caro-kann-structures': { any: ['advantage', 'fork'], all: ['opening'] },
  'structures-choosing-your-first-openings': { any: ['fork', 'hangingPiece'], all: ['opening'] },
  'structures-common-opening-traps': { any: ['attackingF2F7', 'trappedPiece'], all: ['opening'] },
  'structures-connecting-rooks': { any: ['backRankMate', 'castling'] },
  'structures-control-center': { any: ['advantage', 'fork'], all: ['opening'] },
  'structures-database-workflow': { any: ['master', 'masterVsMaster'] },
  'structures-development': { any: ['attackingF2F7', 'exposedKing'], all: ['opening'] },
  'structures-engine-use-opening-prep': { any: ['crushing'], all: ['opening'] },
  'structures-english-structures': { any: ['queensideAttack', 'advantage'] },
  'structures-french-pawn-chains': { any: ['advancedPawn', 'kingsideAttack'] },
  'structures-handling-sidelines': { any: ['trappedPiece', 'fork'], all: ['opening'] },
  'structures-hanging-pawns': { any: ['advancedPawn', 'advantage'] },
  'structures-hedgehog': { any: ['quietMove', 'advantage'] },
  'structures-isolated-queens-pawn-attacking': { any: ['kingsideAttack', 'sacrifice'] },
  'structures-isolated-queens-pawn-blockading': { any: ['defensiveMove', 'advantage'] },
  'structures-keeping-personal-opening-file': { any: ['fork', 'pin'], all: ['opening'] },
  'structures-king-safety-opening': { any: ['exposedKing', 'attackingF2F7'], all: ['opening'] },
  'structures-kings-indian-structures': { any: ['kingsideAttack', 'advancedPawn'] },
  'structures-maroczy-bind': { any: ['advantage', 'quietMove'] },
  'structures-minority-attack': { any: ['queensideAttack', 'advancedPawn'] },
  'structures-model-games': { any: ['masterVsMaster', 'master'] },
  'structures-move-orders-transpositions': { any: ['fork', 'trappedPiece'], all: ['opening'] },
  'structures-open-sicilian': { any: ['sacrifice', 'kingsideAttack'] },
  'structures-panov-structures': { any: ['advantage', 'kingsideAttack'] },
  'structures-repertoire-construction': { any: ['fork', 'pin'], all: ['opening'] },

  // ---- endgames -----------------------------------------------------------
  'endgames-bishop-knight-endings': { any: ['bishopEndgame', 'knightEndgame'] },
  'endgames-bishop-knight-mate': { any: ['mateIn2', 'mateIn3'], all: ['endgame'] },
  'endgames-breakthroughs': { any: ['advancedPawn'], all: ['pawnEndgame'] },
  'endgames-cutting-off-king': { any: ['rookEndgame'] },
  'endgames-distant-opposition': { any: ['pawnEndgame'] },
  'endgames-endgame-transitions': { any: ['capturingDefender'], all: ['endgame'] },
  'endgames-fortresses': { any: ['defensiveMove'], all: ['endgame'] },
  'endgames-frontal-defense-side-checks': { any: ['rookEndgame', 'defensiveMove'] },
  'endgames-fundamental-minor-piece-mate': { any: ['mateIn2', 'mateIn3'], all: ['endgame'] },
  'endgames-key-squares': { any: ['pawnEndgame'] },
  'endgames-king-activity': { any: ['pawnEndgame', 'zugzwang'] },
  'endgames-king-queen-king': { any: ['queenEndgame', 'mateIn2'] },
  'endgames-king-rook-king': { any: ['rookEndgame', 'mateIn2'] },
  'endgames-knight-endings': { any: ['knightEndgame'] },
  'endgames-lucena-position': { any: ['rookEndgame'], rating: [1600, 2400] },
  'endgames-mixed-material-endings': { any: ['queenRookEndgame', 'mix'] },
  'endgames-opposite-colored-bishop-endings': { any: ['bishopEndgame'] },
  'endgames-opposition': { any: ['pawnEndgame', 'zugzwang'] },
  'endgames-pawn-races': { any: ['advancedPawn', 'promotion'], all: ['pawnEndgame'] },
  'endgames-perpetual-check-geometry': { any: ['defensiveMove', 'equality'], all: ['endgame'] },
  'endgames-philidor-position': { any: ['rookEndgame', 'defensiveMove'] },
  'endgames-practical-multi-pawn-rook': { any: ['rookEndgame'] },
  'endgames-queen-endings': { any: ['queenEndgame'] },
  'endgames-rule-square': { any: ['advancedPawn'], all: ['pawnEndgame'] },
  'endgames-same-colored-bishop-endings': { any: ['bishopEndgame'] },
  'endgames-short-side-defense': { any: ['rookEndgame', 'defensiveMove'] },
  'endgames-triangulation': { any: ['zugzwang'] },
  'endgames-vancura-defense': { any: ['rookEndgame', 'defensiveMove'] },

  // ---- mastery ------------------------------------------------------------
  'mastery-active-defense': { any: ['defensiveMove'] },
  'mastery-analyzing-without-engine': { any: ['quietMove', 'long'] },
  'mastery-clock-management': { any: ['mateIn2', 'fork'] },
  'mastery-designing-training-plan': { any: ['fork', 'pin', 'skewer'] },
  'mastery-error-taxonomy': { any: ['hangingPiece', 'defensiveMove'] },
  'mastery-event-simulation': { any: ['crushing', 'long'] },
  'mastery-independent-game-analysis': { any: ['masterVsMaster', 'master'] },
  'mastery-individual-master-cycle': { any: ['superGM', 'masterVsMaster'] },
  'mastery-opening-novelty-research': { any: ['masterVsMaster'], all: ['opening'] },
  'mastery-opponent-preparation': { any: ['masterVsMaster', 'master'] },
  'mastery-passive-defense': { any: ['defensiveMove'] },
  'mastery-performance-audit': { any: ['hangingPiece', 'defensiveMove'] },
  'mastery-playing-complete-slow-game': { any: ['long', 'veryLong'] },
  'mastery-practical-decisions': { any: ['defensiveMove', 'quietMove'] },
  'mastery-recovering-from-loss': { any: ['defensiveMove', 'equality'] },
  'mastery-sparring-training-games': { any: ['crushing', 'long'] },
  'mastery-technical-conversion-against-resistance': { any: ['crushing'], all: ['endgame'] },
  'mastery-title-planning': { any: ['superGM', 'masterVsMaster'] },
  'mastery-tournament-psychology': { any: ['defensiveMove', 'equality'] },
}
